### ISSUE TITLE
Postman: Error inserting user into database

### ISSUE THREAD

**Issue by miketvo** [miketvo/rmit-isys2099-group9-app#42]
# Postman: Error inserting user into database

## POST

- Endpoint: `http://localhost:3000/api/register`
- Body:
  ```json
  {
    "username": "test1",
    "password": "testPwd1",
    "role": "buyer"
  }
  ```

## Error log:

```
npm.cmd run start

> isys2099-group9-app-server@0.0.0 start
> npx nodemon server.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node server.js`
Server is listening on 3000
You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://www.npmjs.com/package/mysql2#using-promise-wrapper, or the mysql2 documentation at https://github.com/sidorares/node-mysql2/tree/master/documentation/en/Promise-Wrapper.md
Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://www.npmjs.com/package/mysql2#using-promise-wrapper, or the mysql2 documentation at https://github.com/sidorares/node-mysql2/tree/master/documentation/en/Promise-Wrapper.md
    at Query.then (C:\Users\vomin\Projects\rmit\rmit-isys2099-group9-app\server\node_modules\mysql2\lib\commands\query.js:43:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error: Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql
2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://www.npmjs.com/package/mysql2#using-promise-wrapper, or the mysql2 documentation at https://github.com/sidorares/node-mysql2/tree/master/documentation/en/Promise-Wrapper.md
    at Query.then (C:\Users\vomin\Projects\rmit\rmit-isys2099-group9-app\server\node_modules\mysql2\lib\commands\query.js:43:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by miketvo** [comment]
Resolved by @LaansDole
